### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ntjoumas**
Added functionality to covid_19 boards. Allows user-selected countries, US States and Canadian provinces.

### CODE REVIEW

**Comment by desigi** [comment]
I noticed an alignment issue when having Quebec selected as a province. You can see what happens [here](https://imgur.com/a/axS5T4z). I think it might have to do with the letter Q.

**Comment by desigi** [comment]
I was able to fix the alignment issue by modifying the font file. This is the end result on the [board](https://imgur.com/a/gQdb9SE).
[This](https://files.desigi.com/index.php/s/xM8JGzYAaWxpBEw) is the modified font I used.

**Comment by ntjoumas** [comment]
Did you add a line in layout.json / fonts.json or just overwrite the existing fonts for font medium?

**Comment by desigi** [comment]
I just overwrote the font. The Q was a 3x6 instead of a 3x5. That's what was causing the issue.

**Comment by ntjoumas** [comment]
Does it matter that one is ttf and the other is otf?

**Comment by desigi** [comment]
I changed the filename (otf file) in the `config/fonts/fonts.json` file for the default, medium_2, and large templates.

**Comment by ntjoumas** [comment]
Ahh - gotcha. Thank you!

**Pull request merged**
