### PR TITLE
Schema Update and removed extra character from config.json.save

### PR DESCRIPTION
**Pull request by sflems**
Extraneous 's' removed. Not sure what effect this may have had if/when used in its current form. It threw errors for me when manipulating the data.

### CODE REVIEW

**Comment by falkyre** [comment]
config.json.save isn't used for anything unless @riffnshred needs it, it likely needs to be removed from the repository

**Comment by sflems** [comment]
Schema update proposed!
-wxalert / weather location and syntax fixed.
-additional properties to false will fail manually added properties not in schema. See commit notes.
-end/stop reference fixed.
-enum values added to provide selection options in json forms.

**Comment by falkyre** [comment]
I'll have to pass it through both the setup app and the main application to ensure that the change doesn't stop those from running.  I don't see an issue with it right now but I am not in front of my dev system to ensure that works.  I'll be back in front of my dev system in a couple of days and will look at the schema.  If all looks good, I'll give @riffnshred the OK to accept the PR

**Comment by sflems** [comment]
Roger that. The config.json.sample file also had a minor change to reflect
this schema if I'm not mistaken. I'll add it to the PR shortly. Have a
great weekend lads!

**Review by falkyre — CHANGES_REQUESTED** [review]
standley_cup_champions should be stanley_cup_champions

These are all the valid boards (from src/nhl_setup/nhl_setup.py)

`        board_list = ['clock','weather','wxalert','wxforecast','scoreticker','seriesticker','standings','team_summary','covid_19','stanley_cup_champions','christmas']
`

**Comment by sflems** [comment]
Typo was fixed above, sorry. It should be in the PR. 👌

**Comment by falkyre** [comment]
I'm running it through the nhl_setup and by adding in the enums for the states, it causes the validation to fail for a known good config.json.  Removing the enums out, the schema and the fastjsonschema library will validate the config.json as expected.  Because that breaks the board from running, I can't accept using your config.json.schema for the core code.  I have even updated to the latest version of the fastjsonschema library I'm using that was release Feb 1, 2021 and the schema you've proposed still breaks core functionality.

**Comment by sflems** [comment]
If additionalProperties are set back to true, but enums remain does it validate an old config? This should work to display the options, but whould allow users to enter incorrect enum values. I'll give it another review tonight and report back.

**Comment by falkyre** [comment]
> If additionalProperties are set back to true, but enums remain does it validate an old config? This should work, but would allow users to enter incorrect enum values or new properties (which would be good for dev/testing anyway).

Nope, setting additionalProperties to true in the whole schema still gives same error with the enums included.  Have you run used teh schema to validate a json?  If so can you include the json that you successfully validated.

**Comment by sflems** [comment]
Sorry @falkyre, missed your message there. For me it's working now with the default configs provided, and configs generated from the setup app.

All additionalPropterties are set to true. Enums remain. Board boots and shows validations, runs its routine. I've attempted several different configs and all seem to be pull correctly. It runs through the setup app without issue as well on my end.

The running config is the provided sample schemas and the updated schema in the most recent commit. Let me know how it tests out!

**Comment by sflems** [comment]
Just a note: By the looks of it the wxforecast board still needs to be defined in the schema. Is it a newer board?

**Comment by falkyre** [comment]
OK, got it figured out and it's related to the wxforecast and the wxalert boards not being in the enum for possible boards to be selected.  wxalert does have it's own configuration and is in the schema.  The wxforecast is part of the weather board settings so it doesn't have it's own schema.  However, both are valid boards to be selected and they are both missing from your board list enums.  Add those back in and it works with the core code again.  Make that change and I'll approve to @riffnshred to accept the PR.

**Review by falkyre — APPROVED** [review]

**Comment by riffnshred** [comment]
Good job bud ! I'll push it to Beta soon

**Comment by riffnshred** [comment]
Side note.... For this season only, the divisions are 
```
"north",
"west",
"south",
"east"
```

I added them to the enum in the schema but you might want to add them to your repo too because otherwise it wont work until next year.

**Comment by sflems** [comment]
Right on thank you, and thanks for the heads up. I've added it on my end.

There are a few more fields that could be expanded on as far as validation goes... but it would take a deep dive and this does the job for now!

**Pull request merged**
