### PR TITLE
Elepolt api fix - version bump to 1.7.0

### PR DESCRIPTION
**Pull request by riffnshred**

### CODE REVIEW

**Comment by pjockey** [comment]
just did a pull from the Master, did the install and receive this:

```
Traceback (most recent call last):
  File "src/main.py", line 5, in <module>
    from renderer.main import MainRenderer
  File "/home/pi/nhl-led-scoreboard/src/renderer/main.py", line 5, in <module>
    from boards.boards import Boards
  File "/home/pi/nhl-led-scoreboard/src/boards/boards.py", line 8, in <module>
    from boards.seriesticker import Seriesticker
  File "/home/pi/nhl-led-scoreboard/src/boards/seriesticker.py", line 6, in <module>
    from data.playoffs import Series
  File "/home/pi/nhl-led-scoreboard/src/data/playoffs.py", line 4, in <module>
    import nhl_api
  File "/home/pi/nhl-led-scoreboard/src/nhl_api/__init__.py", line 1, in <module>
    import nhl_api.game
  File "/home/pi/nhl-led-scoreboard/src/nhl_api/game.py", line 9, in <module>
    from nhl_api_client import Client
ModuleNotFoundError: No module named 'nhl_api_client'
```

VERSION file satates 1.7.0

**Comment by twholbrook** [comment]
I get the same.

**Comment by falkyre** [comment]
Two things. 

1. You need to install the nhl_api_client python library.  
2. If you are running Raspian Buster, it is running Python 3.7 and you will not be able to install the nhl_api_client as it requires Python 3.8 or above.  Upgrade to Bullseye as it is running Python 3.9.  Don't install Bookworm (the latest OS) as there are some Python restrictions that haven't been worked out yet.

**Comment by pjockey** [comment]
> Two things.
> 
> 1. You need to install the nhl_api_client python library.
> 2. If you are running Raspian Buster, it is running Python 3.7 and you will not be able to install the nhl_api_client as it requires Python 3.8 or above.  Upgrade to Bullseye as it is running Python 3.9.  Don't install Bookworm (the latest OS) as there are some Python restrictions that haven't been worked out yet.

Started a fresh with Bullseye, Python3.9  and downloaded 1.7.0 and ran the install. I did have a problem with the rgbmatrix install.

```
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../include -I/usr/include/python3.9 -c rgbmatrix/core.cpp -o build/temp.linux-armv7l-3.9/rgbmatrix/core.o -O3 -Wall
rgbmatrix/core.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
    1 | #error Do not use this file, it is the result of a failed Cython compilation.
      |  ^~~~~
error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
```
Then, after creating a config.json, and attempting to run the script to start the board and also trying to run the sample LED scripts, I get the rgbmatrix module no installed.

```
Traceback (most recent call last):
  File "/home/pi/nhl-led-scoreboard/src/main.py", line 4, in <module>
    from data.scoreboard_config import ScoreboardConfig
  File "/home/pi/nhl-led-scoreboard/src/data/scoreboard_config.py", line 1, in <module>
    from utils import get_file
  File "/home/pi/nhl-led-scoreboard/src/utils.py", line 1, in <module>
    from rgbmatrix import RGBMatrixOptions, graphics
ModuleNotFoundError: No module named 'rgbmatrix'
```
I tried to run `sudo pip3 install rgbmatrix`, but there is no module called rgbmatrix. 

Does this module need to be install from GitHub?

**Comment by falkyre** [comment]
The install.sh script is broken.  Use this one for now, @riffnshred will be updating the script at some point.  https://github.com/falkyre/nhl-led-scoreboard/blob/beta/scripts/install.sh

**Comment by pjockey** [comment]
> The install.sh script is broken. Use this one for now, @riffnshred will be updating the script at some point. https://github.com/falkyre/nhl-led-scoreboard/blob/beta/scripts/install.sh

Gave this script a go and it was a no go. Missing the directory $HOME/nhlsb-venv/bin/activate as requested in line 32. 
```
Activating direnv for python venv...
./scripts/install.sh: line 28: direnv: command not found
Activating python virtual environment...
./scripts/install.sh: line 32: /home/pi/nhlsb-venv/bin/activate: No such file or directory
Updating pip in virtual environment...
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in /home/pi/.local/lib/python3.9/site-packages (23.3.1)
```
I created the directory and the install seemed to go a bit further.

```
Installing collected packages: pillow
  Attempting uninstall: pillow
    Found existing installation: Pillow 10.1.0
    Uninstalling Pillow-10.1.0:
      Successfully uninstalled Pillow-10.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rgbmatrixemulator 0.10.0 requires Pillow>=10.0.1, but you have pillow 8.3.2 which is incompatible.
Successfully installed pillow-8.3.2
Running rgbmatrix installation...
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: cython in /home/pi/.local/lib/python3.9/site-packages (3.0.5)
warning: core.pyx:9:9: Only extern functions can throw C++ exceptions.

Error compiling Cython file:
------------------------------------------------------------
...
cdef class FrameCanvas(Canvas):
    def __dealloc__(self):
        if <void*>self.__canvas != NULL:
            self.__canvas = NULL

    cdef cppinc.Canvas* __getCanvas(self) except *:
         ^
------------------------------------------------------------

core.pyx:61:9: C method '_FrameCanvas__getCanvas' not previously declared in definition part of extension type 'FrameCanvas'

Error compiling Cython file:
------------------------------------------------------------
...

    def __dealloc__(self):
        self.__matrix.Clear()
        del self.__matrix

    cdef cppinc.Canvas* __getCanvas(self) except *:
         ^
------------------------------------------------------------

core.pyx:219:9: C method '_RGBMatrix__getCanvas' not previously declared in definition part of extension type 'RGBMatrix'
warning: core.pyx:93:39: Not all members given for struct 'Options'
warning: core.pyx:93:39: Not all members given for struct 'Options'
warning: core.pyx:94:54: Not all members given for struct 'RuntimeOptions'
warning: core.pyx:94:54: Not all members given for struct 'RuntimeOptions'
make -C ./lib
make[1]: Entering directory '/home/pi/nhl-led-scoreboard/submodules/matrix/lib'
make[1]: Leaving directory '/home/pi/nhl-led-scoreboard/submodules/matrix/lib'
make -C examples-api-use
make[1]: Entering directory '/home/pi/nhl-led-scoreboard/submodules/matrix/examples-api-use'
make -C ../lib
make[2]: Entering directory '/home/pi/nhl-led-scoreboard/submodules/matrix/lib'
make[2]: Leaving directory '/home/pi/nhl-led-scoreboard/submodules/matrix/lib'
make[1]: Leaving directory '/home/pi/nhl-led-scoreboard/submodules/matrix/examples-api-use'
make -C bindings/python build
make[1]: Entering directory '/home/pi/nhl-led-scoreboard/submodules/matrix/bindings/python'
make -C ../../lib
make[2]: Entering directory '/home/pi/nhl-led-scoreboard/submodules/matrix/lib'
make[2]: Leaving directory '/home/pi/nhl-led-scoreboard/submodules/matrix/lib'
/usr/bin/python3 setup.py build --build-lib .
running build
running build_py
running build_ext
building 'core' extension
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../include -I/usr/include/python3.9 -c rgbmatrix/core.cpp -o build/temp.linux-armv7l-3.9/rgbmatrix/core.o -O3 -Wall
rgbmatrix/core.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
    1 | #error Do not use this file, it is the result of a failed Cython compilation.
      |  ^~~~~
error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
make[1]: *** [Makefile:67: build-python] Error 1
make[1]: Leaving directory '/home/pi/nhl-led-scoreboard/submodules/matrix/bindings/python'
make: *** [Makefile:29: build-python] Error 2
make -C ./lib
make[1]: Entering directory '/home/pi/nhl-led-scoreboard/submodules/matrix/lib'
make[1]: Leaving directory '/home/pi/nhl-led-scoreboard/submodules/matrix/lib'
make -C examples-api-use
make[1]: Entering directory '/home/pi/nhl-led-scoreboard/submodules/matrix/examples-api-use'
make -C ../lib
make[2]: Entering directory '/home/pi/nhl-led-scoreboard/submodules/matrix/lib'
make[2]: Leaving directory '/home/pi/nhl-led-scoreboard/submodules/matrix/lib'
make[1]: Leaving directory '/home/pi/nhl-led-scoreboard/submodules/matrix/examples-api-use'
make -C bindings/python build
make[1]: Entering directory '/home/pi/nhl-led-scoreboard/submodules/matrix/bindings/python'
make -C ../../lib
make[2]: Entering directory '/home/pi/nhl-led-scoreboard/submodules/matrix/lib'
make[2]: Leaving directory '/home/pi/nhl-led-scoreboard/submodules/matrix/lib'
/usr/bin/python3 setup.py build --build-lib .
running build
running build_py
running build_ext
building 'core' extension
arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../include -I/usr/include/python3.9 -c rgbmatrix/core.cpp -o build/temp.linux-armv7l-3.9/rgbmatrix/core.o -O3 -Wall
rgbmatrix/core.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
    1 | #error Do not use this file, it is the result of a failed Cython compilation.
      |  ^~~~~
error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
make[1]: *** [Makefile:67: build-python] Error 1
make[1]: Leaving directory '/home/pi/nhl-led-scoreboard/submodules/matrix/bindings/python'
make: *** [Makefile:29: build-python] Error 2
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
make: *** No targets specified and no makefile found.  Stop.
If you didn't see any errors above, everything should be installed!
Installation complete! Play around with the examples in nhl-led-scoreboard/submodules/matrix/bindings/python/samples to make sure your matrix is working.
```

**Comment by falkyre** [comment]
Sorry, that was the wrong one.  That's from my own beta.  This is the one you should use. https://github.com/falkyre/nhl-led-scoreboard/blob/main/scripts/install.sh

**Comment by pjockey** [comment]
> https://github.com/falkyre/nhl-led-scoreboard/blob/main/scripts/install.sh

Another new install with Bullseye minimal, saved the new install script to the setup, it ran without any errors, but when I start the program, I get the following:
```
Traceback (most recent call last):
  File "/home/pi/nhl-led-scoreboard/src/main.py", line 7, in <module>
    from data.scoreboard_config import ScoreboardConfig
  File "/home/pi/nhl-led-scoreboard/src/data/scoreboard_config.py", line 3, in <module>
    from data.colors import Color
  File "/home/pi/nhl-led-scoreboard/src/data/colors.py", line 8, in <module>
    from RGBMatrixEmulator import graphics
ModuleNotFoundError: No module named 'RGBMatrixEmulator'
```
I then `pip3 install RGBMatrixEmulater` and it installed fine, yet when I rung the program again, I get the same error.

I'm running the program with the same flags as I was before the API dropped.

`sudo python3 src/main.py --led-gpio-mapping=adafruit-hat-pwm --led-rows=64 --led-cols=128 --led-panel-type=FM6126B --led-rgb-sequence=BGR --led-brightness=60  --led-slowdown-gpio=2 --led-addr-type=3`

I have seen that it does not like the `--led-addr-type=3` flag tho.

**Comment by falkyre** [comment]
Make sure you aren't cloning any beta and you are only copying that install.sh file from the link above (it's a clone of @riffnshred v1.7.0 release).  The RGBMatrixEmulator is part of the beta.  

`git status`

will show you which branch you are on and 

`git remote -v`

will show you what you cloned.

Or better yet, there are still issues with the API under V1.7.0 and @riffnshred is actively working on another hot fix by the end of the weekend so it's probably better to wait until it gets released.

**Comment by pjockey** [comment]
```
pi@scoreboard:~/nhl-led-scoreboard $ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    config/.default/firstrun

no changes added to commit (use "git add" and/or "git commit -a")
pi@scoreboard:~/nhl-led-scoreboard $ git remote -v
origin	https://github.com/falkyre/nhl-led-scoreboard.git (fetch)
origin	https://github.com/falkyre/nhl-led-scoreboard.git (push)
pi@scoreboard:~/nhl-led-scoreboard $ 
```

**Comment by falkyre** [comment]
Yah, that's my master branch which is messed up at the moment

**Comment by pjockey** [comment]
>Have it installed and the comand gets past the validation of the config.json, yet there is nothing on the screen. I suspect it is the flags for the panel.

**Comment by falkyre** [comment]
The matrix submodule is newer with v1.7.0 so check hzellers repo for the flags that are available now

**Comment by pjockey** [comment]
> The matrix submodule is newer with v1.7.0 so check hzellers repo for the flags that are available now

I playaed with most today and tried numerous different flags and still nothing on the board. So, I decided to try and reinstall the mlb scoreboard. All installed fine, but it too had nothing. Errors looking for PIL or something and I've 2 different versions of pillow being installed between the mlb and nhl boards, so I when back to the nhl board and re-ran the install.sh script, threw up the same starting line but with the flag `--led-panel-type=ICN2037BP` instead of what I had been using, `--led-panel-type=FM6126B` and it started to work, advised it did not recognize the first flag. I then removed the flag altogether and it is working. 

Working start line is as follows in case others having problems with their boards:
`sudo python3 src/main.py --led-gpio-mapping=adafruit-hat-pwm --led-rows=64 --led-cols=128 --led-rgb-sequence=BGR --led-brightness=60  --led-slowdown-gpio=2 --led-row-addr-type=3`

I turned on the weather (EC) in the config.json, but it errored out.

I starting to think that multiple scoreboards are not going to be able to reside on the same micro sd card and play nicely.

**Comment by falkyre** [comment]
Virtual Environments are the only (and soon to be the forced) way to do that.  Bookworm doesn't allow you to automatically install anything for Python as root.  Python 3.11 strongly suggests to use the venv instead.  My image uses a virtual environment already so it's ready for when some of the pieces I use from other people are fixed under bookworm.

**Comment by pjockey** [comment]
> Virtual Environments are the only (and soon to be the forced) way to do that. Bookworm doesn't allow you to automatically install anything for Python as root. Python 3.11 strongly suggests to use the venv instead. My image uses a virtual environment already so it's ready for when some of the pieces I use from other people are fixed under bookworm.

I saw this, I installed the image yesterday and saw the virtual environment.

**Pull request merged**
