### PR TITLE
Ability to run in terminal

### PR DESCRIPTION
**Pull request by ELepolt**
Since the RGB matrix that I wanted was out of stock, I made some changes to allow this to run on terminal instead (with color).

### CODE REVIEW

**Comment by riffnshred** [comment]
Neat !!! I'm not going to merge it yet there is new stuff coming in soon and I want to test that properly first.

**Comment by falkyre** [comment]
Do you have screenshots of what it looks like?  It looks pretty straightforward.  I might add it to my weather branch.

**Comment by ELepolt** [comment]
But I did just run into a problem running it on an LCD screen on my pi, so I'm going to dig in to that a bit today.

nhlscoreboard

**Comment by jeepdrvr71** [comment]
Falykre any news on if the weather component is going to be rolled into the main program?

**Comment by ELepolt** [comment]
@falkyre @riffnshred, turns out my issue was just that the pushbutton flag is set to true by default. So my the program was crashing because it was trying to do things it couldn't.

**Comment by falkyre** [comment]
@jeepdrvr71 no idea. It's being tested by @riffnshred to.see if he wants to merge it.

**Comment by falkyre** [comment]
@ELepolt so this generates everything using ASCII for the terminal?  Nice.

**Comment by ELepolt** [comment]
I snagged the code from this repo: https://github.com/nikhilkumarsingh/terminal-image-viewer

**Comment by riffnshred** [comment]
@ELepolt that's pretty neat !!! 

@jeepdrvr71 Been testing a previous version of the weather app but @falkyre been fixing some issues. I'll pull it right now into the dev branch. I think the terminal viewer is a great feature too so I'll release both together after I test them.

**Comment by riffnshred** [comment]
@ELepolt  can you open an other pull request but on the Beta branch instead ? I don't merge any pullrequest directly to master as I test everything first.

**Comment by ELepolt** [comment]
@riffnshred makes sense, will do as soon as I figure out if this new color issue is a computer settings issue, or a code issue!

**Comment by riffnshred** [comment]
Cool, Thanks !!!

**Pull request closed without merging**
