### PR TITLE
Terminal mode

### PR DESCRIPTION
**Pull request by ELepolt**
Terminal mode along with some notes in the readme.

VS Code automatically added those parts on the Table of Contents when I hit save. Let me know if you want me to take them out

### CODE REVIEW

**Comment by riffnshred** [comment]
All good since this is the beta branch and the part that was added will change when I release anyway. 

Thanks man, taking a look at it.

**Comment by falkyre** [comment]
@ELepolt What issues were you seeing with the pushbutton enabled?  I ran the code last night with the pushbutton enabled and the terminal stuff worked fine.  Granted I did not have a pushbutton actually hooked up but the config code shouldn't impact anything in code.  Where the issues typically arise is if you are hooking up the pushbutton to a GPIO pin that is already used, then funny stuff happens.

**Comment by ELepolt** [comment]
```
INFO (08:47:45): /sbin/reboot <-- reboot || poweroff --> /sbin/poweroff
/home/evan/.local/lib/python3.6/site-packages/gpiozero/devices.py:279: PinFactoryFallback: Falling back from rpigpio: No module named 'RPi'
  'Falling back from %s: %s' % (name, str(e))))
/home/evan/.local/lib/python3.6/site-packages/gpiozero/devices.py:279: PinFactoryFallback: Falling back from rpio: No module named 'RPIO'
  'Falling back from %s: %s' % (name, str(e))))
/home/evan/.local/lib/python3.6/site-packages/gpiozero/devices.py:279: PinFactoryFallback: Falling back from pigpio: No module named 'pigpio'
  'Falling back from %s: %s' % (name, str(e))))
/home/evan/.local/lib/python3.6/site-packages/gpiozero/devices.py:279: PinFactoryFallback: Falling back from native: unable to locate Pi revision in /proc/device-tree or /proc/cpuinfo
  'Falling back from %s: %s' % (name, str(e))))
Traceback (most recent call last):
  File "src/main.py", line 68, in <module>
    run()
  File "src/main.py", line 59, in run
    pushbutton = PushButton(data,matrix,sleepEvent)
  File "/home/evan/Documents/Code/nhl-led-scoreboard/src/sbio/pushbutton.py", line 89, in __init__
    self.button=Button(self.use_button, hold_time=self.poweroff_duration)
  File "/home/evan/.local/lib/python3.6/site-packages/gpiozero/devices.py", line 124, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/evan/.local/lib/python3.6/site-packages/gpiozero/input_devices.py", line 432, in __init__
    bounce_time=bounce_time, pin_factory=pin_factory)
  File "/home/evan/.local/lib/python3.6/site-packages/gpiozero/mixins.py", line 383, in __init__
    super(HoldMixin, self).__init__(*args, **kwargs)
  File "/home/evan/.local/lib/python3.6/site-packages/gpiozero/input_devices.py", line 182, in __init__
    pin_factory=pin_factory)
  File "/home/evan/.local/lib/python3.6/site-packages/gpiozero/mixins.py", line 197, in __init__
    super(EventsMixin, self).__init__(*args, **kwargs)
  File "/home/evan/.local/lib/python3.6/site-packages/gpiozero/input_devices.py", line 98, in __init__
    super(InputDevice, self).__init__(pin, pin_factory=pin_factory)
  File "/home/evan/.local/lib/python3.6/site-packages/gpiozero/devices.py", line 512, in __init__
    super(GPIODevice, self).__init__(**kwargs)
  File "/home/evan/.local/lib/python3.6/site-packages/gpiozero/devices.py", line 243, in __init__
    Device.pin_factory = Device._default_pin_factory()
  File "/home/evan/.local/lib/python3.6/site-packages/gpiozero/devices.py", line 280, in _default_pin_factory
    raise BadPinFactory('Unable to load any default pin factory!')
gpiozero.exc.BadPinFactory: Unable to load any default pin factory!
```

**Comment by falkyre** [comment]
Yup, nothing to do with your code.  Probably should add to the install to at least installing a base gpio pin factory.  Out of the box, raspian "should" have it.  If you install RPi.GPIO, that will remove that error.

$ sudo apt-get update
$ sudo apt-get install python-rpi.gpio python3-rpi.gpio

Or sudo pip3 install  RPi.GPIO

**Comment by falkyre** [comment]
@riffnshred Can you update @ELepolt readme change to takeout setting the pushbutton to false?  I'll look into trying to handle that default pin factory error

**Comment by ELepolt** [comment]
How do you feel about linking to other repositories? In regards to making sure the 'proper drivers are installed' I was going to link this https://github.com/goodtft/LCD-show which is where I found all the drivers for all the types of screens?

**Comment by riffnshred** [comment]
@falkyre you want to take out the option to enable or disable the button?
@ELepolt  you mean making it a submodule? If you mean link it in the read me with your instructions, no problem. If you mean adding it as a submodule I'd prefer not since what it's for is not part of the core project and I try to keep the repo as clean as possible.

**Comment by ELepolt** [comment]
I was just going to link it

**Comment by riffnshred** [comment]
Yup no problems man.  You got it running on a TFT screen on a raspberry pi ? if so, send pics

**Comment by ELepolt** [comment]
Heck yeah! Sadly, like I put in the README, you have to actually boot up a GUI. But once you're in you can get it running and full screen without a mouse.

I have it on my pi3, and the logo will 'jump' every now and then when it's scrolling as it's rewriting but it's pretty good.

https://gfycat.com/faroffheavygoose

avs

**Comment by riffnshred** [comment]
Neat !!!

**Pull request merged**
